USING SYSTEM;
USING SYSTEM.COLLECTIONS.GENERIC;
USING SYSTEM.LINQ;
USING SYSTEM.TEXT;
USING SYSTEM.THREADING.TASKS;
USING SYSTEM.IO;

NAMESPACE ITMO.CSCOURSE2021.LAB07_03.REFTYPES.COPYFILEUPPER
{
    // CLASS TO CREATE AN UPPER CASE COPY OF A FILE
    // TEST PROGRAMM RUN FROM COMMAND LINE

    CLASS COPYFILEUPPER
    {
        STATIC VOID MAIN()
        {
            STRING SFROM, STO;
            STREAMREADER SRFROM;
            STREAMWRITER SWTO;

            CONSOLE.WRITELINE("ENTER NAME INPUT FILE:");
            SFROM = CONSOLE.READLINE();
            CONSOLE.WRITELINE("ENTER NAME OUTPUT FILE:");
            STO = CONSOLE.READLINE();

            CONSOLE.WRITELINE("COPY FROM {0} TO {1}", SFROM, STO);
            TRY
            {
            
                SRFROM = NEW STREAMREADER(SFROM);       //CREATE A NEW OBJECT OF TYPE STREAMREADER
                SWTO = NEW STREAMWRITER(STO);           //CREATE A NEW OBJECT OF TYPE STREAMWRITER

                WHILE (SRFROM.PEEK() != -1)                 //STREAMREADER.PEEK METHOD FROM SYSTEM.IO
                {
                    STRING SBUFFER = SRFROM.READLINE();     //STREAMREADER.READLINE METHOD FROM SYSTEM.IO
                    SBUFFER = SBUFFER.TOUPPER();            //STRING.TOUPPER METHOD FROM SYSTEM
                    SWTO.WRITELINE(SBUFFER);                //STREAMWRITER.WRITELINE METHOD FROM SYSTEM.IO
                }
                SRFROM.CLOSE();                         //CLOSE INPUT STREAM
                SWTO.CLOSE();                           //CLOSE OUTPUT STREAM
            }
            CATCH (FILENOTFOUNDEXCEPTION)
            {
                CONSOLE.WRITELINE("INPUT FILE NOT FOUND");
            }
            CATCH (EXCEPTION E)
            {
                CONSOLE.WRITELINE("UNEXPECTED EXCEPTION");
                CONSOLE.WRITELINE(E.TOSTRING());
            }

        }
    }
}
